download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/netapp-ontap-22.12.0.tar.gz
format_version: 1.0.0
name: ontap
namespace: netapp
server: https://galaxy.ansible.com/api/
signatures: []
version: 22.12.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/netapp/ontap/versions/22.12.0/
