download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-windows-2.3.0.tar.gz
format_version: 1.0.0
name: windows
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/windows/versions/2.3.0/
