download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/chocolatey-chocolatey-1.5.1.tar.gz
format_version: 1.0.0
name: chocolatey
namespace: chocolatey
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.5.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/chocolatey/chocolatey/versions/1.5.1/
