---
- name: Gather and Store Historical Data of Installed Windows Updates
  hosts: win_hosts
  gather_facts: no
  tasks:
    - name: Get Installed Updates from Win32_QuickFixEngineering
      win_shell: |
        Get-WmiObject -Class Win32_QuickFixEngineering | Where-Object { $_.HotFixID -match "^KB" } | Select-Object -Property Description, HotFixID, InstalledOn | ConvertTo-Json -Compress
      register: wmi_updates

    - name: Get Installed Updates from Win32_ReliabilityRecords
      win_shell: |
        Get-WmiObject -Class Win32_ReliabilityRecords | Where-Object { $_.InsertionStrings -match "KB[0-9]+" } | Select-Object -Property EventIdentifier, EventType, ProductName, InsertionStrings, TimeGenerated | ConvertTo-Json -Compress
      register: reliability_updates

    - name: Prepare data for storage
      set_fact:
        combined_updates: {
          "wmi_updates": "{{ wmi_updates.stdout | from_json }}",
          "reliability_updates": "{{ reliability_updates.stdout | from_json }}",
          "hostname": "{{ inventory_hostname }}"
        }

    #- name: Save combined updates to file
    #  copy:
    #    content: "{{ combined_updates | to_nice_json }}"
    #    dest: "/tmp/combined_updates.json"
    #  delegate_to: localhost

    - name: Send historical data to database
      ansible.builtin.uri:
        url: "http://127.0.0.1/post/store_windows_patching_update_history.php"
        method: POST
        body_format: json
        body: "{{ combined_updates }}"
        headers:
          Content-Type: application/json
        status_code: 200
        return_content: True
      register: postoutput
      delegate_to: localhost
      check_mode: no

    #- name: Save post output to file
    #  copy:
    #    content: "{{ postoutput | to_nice_json }}"
    #    dest: "/tmp/postoutput.json"
    #  delegate_to: localhost

    - name: Display database post status
      ansible.builtin.debug:
        msg:
          - "Data sent to database"
          - "{{ postoutput }}"
          #- "{{ combined_updates }}"