---
- name: Display Facts
  hosts: Link_Control:VNIA4
  vars:
    - ansible_remote_tmp: /var/tmp/ans
    - host_key_checking: false
  gather_facts: yes
  tasks:
  - name: Send facts to database
    ansible.builtin.uri:
      url: "http://127.0.0.1/post/store_facts.php?taskid=1"
      method: POST
      body_format: json
      body: "{{ ansible_facts }}"
      headers:
        Content-Type: application/json
      status_code: 200
      return_content: True
    register: postoutput1
    delegate_to: localhost

  - name: Print status of posted message
    ansible.builtin.debug:
      msg:
        - "Post output"
        - "{{ postoutput1 }}"

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
