---
- hosts: localhost
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Get VM Info
    community.vmware.vmware_guest_info:
      hostname: vcsa.infra.local
      username: ansible-test@infra.local
      password: DFyuqwhjty34JK@#23@#
      validate_certs: no
      name: "vNIA4 (TGS J114)(Stack2)"
      schema: "summary"
      datacenter: INFRA
      folder: /Labs/DEV/
    delegate_to: localhost
    register: info

  - name: Display VM Info
    ansible.builtin.debug:
      msg:
        - "VM Info"
        - "{{ info.instance.hw_eth0.macaddress }}"
