---
- hosts: localhost
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Get VM Info
    community.vmware.vmware_guest_info:
      hostname: vcsa.infra.local
      username: ansible-test@infra.local
      password: DFyuqwhjty34JK@#23@#
      validate_certs: no
      name: "vNIA4 (TGS J114)(Stack2)"
      schema: "summary"
      datacenter: INFRA
      folder: /Labs/DEV/
    delegate_to: localhost
    register: info

  - name: Display VM Info
    ansible.builtin.debug:
      msg:
        - "VM Info"
        - "{{ info.instance.hw_eth0.macaddress }}"

  - name: Config File /etc/udev/rules.d/70-persistent-net.rules
    ansible.builtin.copy:
      dest: /playbooks/test-net-rules.txt
      content: |
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth0.macaddress }}", ATTR{type}=="1", NAME="net0"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth1.macaddress }}", ATTR{type}=="1", NAME="net1"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth2.macaddress }}", ATTR{type}=="1", NAME="net2"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth3.macaddress }}", ATTR{type}=="1", NAME="net3"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth4.macaddress }}", ATTR{type}=="1", NAME="net4"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth5.macaddress }}", ATTR{type}=="1", NAME="net5"
        SUBSYTEM=="net", DRIVERS=="?*", ACTION=="add", ATTR{address}=="{{ info.instance.hw_eth6.macaddress }}", ATTR{type}=="1", NAME="net6"
    become: no
    delegate_to: localhost
     
