---
- hosts: win
  tasks:
    - name: Basic-Update
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        log_path: c:\ansible_wu1.txt
        reboot: true
        reboot_timeout: 600


