---
- hosts: "{{ target }}"
  tasks:
    - name: Uninstall Java x64
      win_package:
        product_id: '{77924AE4-039E-4CA4-87B4-2F64180421F0}'
        state: absent
    - name: Uninstall Java x32
      win_package:
        product_id: '{77924AE4-039E-4CA4-87B4-2F32180421F0}'
        state: absent


