---
- name: Host Vars Test
  hosts: FMV.J114.ARMY.MIL
  gather_facts: yes
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: Print hostvar
    ansible.builtin.debug:
      var: ogs_win_7zip

