---
- hosts: win
  tasks:
    - name: Check
      win_updates:
        category_names:
          -SecurityUpdates
          -CriticalUpdates
          -UpdateRollups
        state: searched
        log_path: c:\ansible_wu.txt

