---
- hosts: "{{ target }}"
  tasks:
    - name: Install Firefox
      win_package:
        path: http://164.225.186.93/software/Firefox%20Setup%20128.6.0esr.exe
        product_id: Mozilla Firefox 128.6.0 ESR (x64 en-US)
        arguments: /S
        state: present

