---
- hosts: Win_Servers
  tasks:
    - name: CPU usage
      ansible.windows.win_powershell:
        script: |
          $cpuUtil = (get-counter -Counter "\Processor(_Total)\% Processor Time" -SampleInterval 1 -MaxSamples 10 | select -ExpandProperty countersamples | select -ExpandProperty cookedvalue | Measure-Object -Average).average
          [math]::Round($cpuUtil*100,2)
      register: cpu_results

    - name: Memory
      ansible.windows.win_powershell:
        script: |
          $mem = Get-CIMInstance Win32_OperatingSystem | Select FreePhysicalMemory,TotalVisibleMemorySize
          $availP = [math]::Round(($mem.FreePhysicalMemory/$mem.TotalVisibleMemorySize)*100,2)
          $availP
      register: mem_results

    - name: Disk Space
      ansible.windows.win_powershell:
        script: |
          $drive = Get-WmiObject Win32_LogicalDisk -Filter "DriveType = 3" | Select -First 1
          $driveAvail = [math]::Round(($drive.FreeSpace/$drive.Size)*100,2)
          $driveAvail
      register: disk_space

    - name: Service Status
      ansible.windows.win_powershell:
        script: |
          $drive = Get-WmiObject Win32_LogicalDisk -Filter "DriveType = 3" | Select -First 1
          $driveAvail = [math]::Round(($drive.FreeSpace/$drive.Size)*100,2)
          $driveAvail
      register: service_status


    - name: Usage Stats
      debug:
        msg: 
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "Ansible Hostname: {{ ansible_facts.hostname }}"
          - "OS Family: {{ ansible_facts.os_family }}"
          - "CPU Usage: {{ cpu_results.output }}%"
          - "RAM Usage: {{ mem_results.output }}%"
          - "Disk Space Free: {{ disk_space.output }}%"
      register: win_perf

    - name: Send facts to database
      ansible.builtin.uri:
        url: "http://127.0.0.1/post/store_facts.php?taskid=1"
        method: POST
        body_format: json
        body: "{{ win_perf }}"
        headers:
          Content-Type: application/json
        status_code: 200
        return_content: True
      register: postoutput1
      delegate_to: localhost
      check_mode: no

    - name: Display db Post Status
      ansible.builtin.debug:
        msg:
          - "Patching Status"
          - "{{ postoutput1 }}"



