---
- hosts: "{{ target }}"
  tasks:
    - name: Install or Update Notepad++
      win_package:
        path: http://164.225.186.93/software/npp.8.7.5.Installer.x64.exe
        product_id: Notepad++
        creates_path: C:\Program Files\Notepad++\notepad++.exe
        creates_version: 8.7.5
        arguments: /S
        state: present

