---
- hosts: Win_Servers
  tasks:
    - name: Update Win_Servers
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
          - Update Rollups
        log_path: c:\ansible_wu1.txt
        reboot: true
        reboot_timeout: 600


