---
- hosts: "{{ target }}"
  tasks:
    - name: Update Microsoft Visual C++ 2015-2019 Redist (x86)
      win_package:
        path: http://164.225.186.93/software/VC_redist.x86.exe
        product_id: '{C2BB95AA-90F3-4891-81C1-A7E565BB836C}'
        arguments:
          - /install
          - /quiet
          - /norestart
        state: present

    - name: Update Microsoft Visual C++ 2015-2019 Redist (x64)
      win_package:
        path: http://164.225.186.93/software/VC_redist.x64.exe
        product_id: '{382F1166-A409-4C5B-9B1E-85ED538B8291}'
        arguments:
          - /install
          - /quiet
          - /norestart
        state: present
