---
- hosts: "{{ target }}"
  tasks:
    - name: Install WinSCP
      win_package:
        path: http://164.225.186.93/software/WinSCP-6.3.6-Setup.exe
        product_id: winscp3_is1
        creates_path: C:\Program Files (x86)\WinSCP\WinSCP.exe
        creates_version: 6.3.6
        arguments:
          - /SILENT
          - /ALLUSERS
        state: present

