---
- hosts: "{{ target }}"
  tasks:
    - name: Install Putty
      win_package:
        path: http://164.225.186.93/software/putty-64bit-0.82-installer.msi
        product_id: '{A2B01D7C-F700-4ECC-8C7F-79C597CC7628}'
        arguments:
          - /qn
          - /norestart
        state: present

