---
- hosts: "{{ target }}"
  tasks:
    - name: Install Java x64
      win_package:
        path: http://164.225.186.92/software/jre-8u421-windows-x64.exe
        product_id: '{77924AE4-039E-4CA4-87B4-2F64180421F0}'
        arguments:
          - /s
          - INSTALLDIR=C:\Program Files\Java\jre8
          - REBOOT=Suppress
          - AUTO_UPDATE=0
        state: present
    - name: Install Java x32
      win_package:
        path: http://164.225.186.92/software/jre-8u421-windows-i586.exe
        product_id: '{77924AE4-039E-4CA4-87B4-2F32180421F0}'
        arguments:
          - /s
          - INSTALLDIR=C:\Program Files (x86)\Java\jre8
          - REBOOT=Suppress
          - AUTO_UPDATE=0
        state: present


